config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  get 'about', to: 'pages#about'
  
  resources :articles

  get 'signup', to: 'users#new'

  post 'users', to: 'users#create'

  resources :users, except: [:new]

  get 'introduction', to: 'pages#introduction'

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	 belongs_to :user
	 validates :title, presence: true, length: {minimum: 3, maximum: 50} 
	 validates :description, presence: true, length: {minimum: 10, maximum: 1000} 
	 validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles
	before_save { self.email = email.downcase }
	validates :username, presence: true,
			  uniqueness: {case_sensitive: false},
			  length: {minimum: 3, maximum: 25}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i	
	validates :email, presence: true, length: { maximum: 105 },		  
			  uniqueness: {case_sensitive: false},
			  format: {with:  VALID_EMAIL_REGEX}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  	
  def logged_in?
  	!!current_user
  end

  def require_user
  	if !logged_in?
  		flash[:danger] = "You must be logged in to perform that action"
  		redirect_to root_path
  	end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :update, :show, :destroy] 

	def index
	 	if logged_in?
 	 	 @articles = Article.paginate(page: params[:page], per_page: 5)
 		else
 		flash[:danger] = "You must be logged in to perform that action"
 		 redirect_to root_path
 		end
	end

	def new
		@article = Article.new
	end
	
	def edit
	end

	def create
		#render palain: params[:article].inspect
		@article = Article.new(article_params)
		@article.user = User.first
		if @article.save
			flash[:success] = "Article was successfully created."
			redirect_to article_path(@article)
		else
			render 'new'
		end	
	end

	def update
		if @article.update(article_params)
			flash[:success] = "Article was successfully update."
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def show
	end

	def destroy
		@article.destroy
		flash[:danger] = "Article was successfully delete."
		redirect_to articles_path
	end

	private
	def set_article
		@article = Article.find(params[:id])
	end
	def article_params
		params.require(:article).permit(:title, :description)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def introduction
  
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		session[:user_id] = user.id
  		flash[:success] = "You have successfully logged in"
  		redirect_to user_path(user)
	else
		flash[:danger] = "There was something wrong with your login information"
		render 'new'
	end

  end

  def destroy
  		session[:user_id] = nil
  		flash[:success] = "You have logged out"
  		redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show]
	def index
		@users = User.paginate(page: params[:page], per_page: 5)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Welcome come to Fun Blog #{@user.username}"
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:success] = "Your account was updated successfully"
			redirect_to articles_path
		else
			render 'edit'
		end	
	end

	def show
		@user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
	end

	private
	def user_params
	  params.require(:user).permit(:username, :email, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options = {size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url,alt: user.username, class: "img-circle")
	end
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article|%>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="well well-lg">
				<div class="article-title">
					<%=link_to article.title, article_path(article) %>
				</div>
				<div class="article-body">
					<%= truncate(article.description, length: 100)%>
					<div class="article-meta-details">
						<small>Created by: <%= article.user.username if article.user%>,
								<%= time_ago_in_words(article.created_at) %> ago,
							    last updated: <%= time_ago_in_words(article.updated_at)%> ago
						</small>
					</div>
				</div>
				<div class="article-actions">
				<%=link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary"%>
				<%=link_to "Delete this article", article_path(article), method: :delete, data: {confirm: "Are you sure want to delete the artical?"}, class: "btn btn-xs btn-danger"%>
				</div>
			</div>
		</div>
	</div>
<%end%>

app/views/articles/_form.html.erb
<%=render "shared/errors", obj: @article%>
<div class="row">
	<div class="col-xs-12">
		<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f|%>
		<div class="form-group">
			<div class="control-label col-sm-2">
					<%= f.label :title%><br/>
			</div>
			<div class="col-sm-8">		
					<%= f.text_field :title, class: "form-control",placeholder:"Title of article", autofocus: true%>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-sm-2">
					<%= f.label :description%><br/>
			</div>
			<div class="col-sm-8">
					<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of article"%>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-10 col-sm-offset-2">
					<%=f.submit class: "btn btn-primary btn-lg"%>
			</div>
		</div>
		<%end%>
		<div class="col-xs-4 col-xs-offset-4">	
			[ <%=link_to "Cancel request and return to aricles listing", articles_path%> ]
		</div>
	</div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing erticle</h1>
<%= render 'form', obj: @articles%>

app/views/articles/index.html.erb
<h1 align="center">Listing all article</h1>
<div align="center">
	<%=will_paginate%>
</div>
<%=render 'article', obj: @articles%>
<div align="center">
	<%=will_paginate%>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>
<%= render 'form'%>

app/views/articles/show.html.erb
<h2 align="center">Title: <%=@article.title%></h2>
<div class="well col-xs-8 col-xs-offset-2">
<% if @article.user %>
		<ul class="listing">
			<div class="row center">
				<div class="col-md-4 col-md-offset-4">
					<li>Created by:</li>
					<li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
					<li class="article-title">
					  <%= link_to @article.user.username, user_path(@article.user) %>
					</li>
					<li><small>
					<%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
					</small></li>
				</div>
			</div>
		</ul>
<%end%>
	<h4 class="center description"><strong>Description:</strong></h4>
		<hr>
			<div class="content"><%= simple_format(@article.description)%></div>
	<div class="article-actions">
		<%=link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary"%>
		<%=link_to "Delete this article", article_path(@article), method: :delete, data: {confirm: "Are you sure swant to delete the artical?"}, class: "btn btn-xs btn-danger"%>
		<%=link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Coppyright &copy; <a href="http://guides.rubyonrails.org/">Ruby on Rails open education </a>
			by <a href="https://www.facebook.com/tai.tpm">Tai-Tpm</a>
		</small>
		<nav>
		<ul>
			<li><%=link_to "About", about_path%></li>
		</ul>
		</nav>
	</footer>	
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg|%>
		<div class="alert alert-<%="#{name}"%>">
			<a href="#" class="close" data-dismiss="alert">&#215;</a>
			<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
		</div>
		<%end%>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Fun Blog", root_path, class: "navbar-brand", id:"logo"%>	
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%=link_to "Article", articles_path%></li>
        <li><%=link_to "Support", introduction_path%></li>
        <% if logged_in?%>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%=link_to "Create new article", new_article_path%></li>
            <li role="separator" class="divider"></li>
            <li><%=link_to "view all articles", articles_path%></li></li>
          </ul>
        </li>
        <%end%>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in?%>
              <li><%= link_to current_user.username,current_user %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-cog"></i><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", users_path%></li>
                  <li><%= link_to "Edit", edit_user_path(current_user.id)%></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Sign out", logout_path, method: :delete%></li>
        <%else%>
            <li><%=link_to "Sign up", signup_path%></li>
            <li><%=link_to "Log in", login_path%></li>
        <%end%>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FunBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%=render 'layouts/navigation'%>
    <%=render 'layouts/messages'%>
    <div class="container">
      <%= yield %>
    </div>
    <%=render 'layouts/footer'%>
    <!-- //<%= debug(params) if Rails.env.development? %>  -->
  </body>
</html>

app/views/pages/about.html.erb
<h1 align="center">About</h1>
<hr>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam et lobortis nunc. Morbi semper velit id dui vestibulum, nec imperdiet sem eleifend. Donec sed fringilla elit, eu efficitur nunc. Phasellus et semper nisl. Praesent varius tempus quam, a ullamcorper enim pharetra vel. Duis facilisis elit metus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris vitae ultricies nisl. Cras arcu dui, porttitor sed leo et, venenatis aliquam lectus. Donec sed purus quis elit hendrerit placerat non vitae felis. Mauris ut mollis justo, eu dictum odio. Sed dapibus eu mi ut scelerisque. Nullam accumsan vestibulum diam ut condimentum. </p>
<p>Nunc ac semper tortor. Sed congue auctor risus eget scelerisque. Fusce eleifend orci volutpat est commodo accumsan. Pellentesque tincidunt vitae nulla vitae efficitur. Fusce tellus tortor, consequat in lobortis nec, pellentesque et libero. Etiam at sollicitudin lectus, at aliquam urna. Phasellus ac dui nisi. Quisque convallis ligula quis ipsum venenatis suscipit. Proin in nisi a enim sollicitudin semper sed sed metus. Suspendisse potenti. Aliquam dignissim efficitur mauris non pharetra. Sed sed condimentum nunc. Donec eget erat in nisl molestie gravida eu porta risus. </p>
<p>Nam sed metus felis. Nullam maximus fermentum sodales. Fusce scelerisque metus dui, id placerat metus tempor sed. Praesent quis ex at ex vulputate pharetra. Etiam sed scelerisque tellus, sed sagittis arcu. In non mauris consectetur arcu facilisis venenatis. Nam lectus orci, volutpat eu odio eget, cursus sollicitudin neque. Praesent quis sollicitudin quam. Duis ut mi at erat congue hendrerit id sed quam. Aenean semper odio eget erat tristique, in tempor diam suscipit. Integer vitae justo scelerisque, gravida neque a, egestas eros. Donec consectetur tempor pretium. Fusce ac nibh eu justo blandit cursus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque enim tellus, euismod id risus sit amet, ultricies eleifend metus. Pellentesque et ante et nulla convallis pellentesque. </p>
<p>Curabitur molestie libero ut massa rhoncus, nec porta sapien malesuada. Fusce congue non risus quis consectetur. Phasellus vitae nisl nec odio finibus gravida a eu lorem. Morbi blandit nulla ac diam rhoncus volutpat. Mauris nec tortor quis urna iaculis accumsan. Nulla laoreet augue tellus, eget condimentum quam congue sit amet. Pellentesque lacinia nisl condimentum nulla ultricies condimentum. Nunc sed vulputate nibh. Pellentesque nisl diam, volutpat nec interdum in, blandit sed diam. Aliquam vel lectus maximus, tincidunt velit id, fringilla purus. Cras quis massa non magna accumsan aliquet. Aliquam vel nisl sapien. Sed ut nisl porttitor, fringilla ante non, imperdiet ipsum. </p>
<p>Mauris luctus nibh mi, ut scelerisque nunc interdum nec. Ut elementum massa commodo sapien gravida blandit. Duis molestie venenatis hendrerit. Aliquam erat volutpat. Ut posuere dui dolor, sit amet pulvinar turpis euismod ac. Quisque tincidunt neque sit amet lectus molestie, sed consectetur nisl efficitur. Praesent malesuada, lorem vitae sagittis condimentum, enim orci ornare odio, sit amet interdum nisi ex at dolor. Donec elementum posuere quam, sollicitudin luctus nisl ultricies ut. Duis eu vestibulum ipsum. Quisque vitae ipsum iaculis ante molestie gravida. Nunc vehicula ut ex vitae pellentesque. Maecenas elementum rutrum risus, id ornare tellus tempor non. Ut posuere metus at ipsum posuere aliquam. Suspendisse eleifend dolor ac dictum pharetra. Nulla a sagittis ante, tristique tristique lorem. Praesent vitae eros malesuada, consequat nulla a, fermentum diam. </p>

<p><%= link_to "Home", root_path%></p>


<style>
	h1 {
	    font-size: 70px;
	    line-height: 90px;
	    font-family: DauphinPlain;
	    font-weight: 400;
	}
	hr {
	    border: 0;
	    height: 1px;
	    background-image: linear-gradient(to right,rgba(0,0,0,0),rgba(0,0,0,.75),rgba(0,0,0,0));
	}
	p{
		text-align: justify;
		margin: 0 0 15px;
	}
</style>

app/views/pages/home.html.erb
<div class="center jumbotron">
<h1>Fun Blog</h1>
</div>

app/views/pages/introduction.html.erb
<h1 align="center">Support</h1>
<hr>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam et lobortis nunc. Morbi semper velit id dui vestibulum, nec imperdiet sem eleifend. Donec sed fringilla elit, eu efficitur nunc. Phasellus et semper nisl. Praesent varius tempus quam, a ullamcorper enim pharetra vel. Duis facilisis elit metus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris vitae ultricies nisl. Cras arcu dui, porttitor sed leo et, venenatis aliquam lectus. Donec sed purus quis elit hendrerit placerat non vitae felis. Mauris ut mollis justo, eu dictum odio. Sed dapibus eu mi ut scelerisque. Nullam accumsan vestibulum diam ut condimentum. </p>
<p>Nunc ac semper tortor. Sed congue auctor risus eget scelerisque. Fusce eleifend orci volutpat est commodo accumsan. Pellentesque tincidunt vitae nulla vitae efficitur. Fusce tellus tortor, consequat in lobortis nec, pellentesque et libero. Etiam at sollicitudin lectus, at aliquam urna. Phasellus ac dui nisi. Quisque convallis ligula quis ipsum venenatis suscipit. Proin in nisi a enim sollicitudin semper sed sed metus. Suspendisse potenti. Aliquam dignissim efficitur mauris non pharetra. Sed sed condimentum nunc. Donec eget erat in nisl molestie gravida eu porta risus. </p>
<p>Nam sed metus felis. Nullam maximus fermentum sodales. Fusce scelerisque metus dui, id placerat metus tempor sed. Praesent quis ex at ex vulputate pharetra. Etiam sed scelerisque tellus, sed sagittis arcu. In non mauris consectetur arcu facilisis venenatis. Nam lectus orci, volutpat eu odio eget, cursus sollicitudin neque. Praesent quis sollicitudin quam. Duis ut mi at erat congue hendrerit id sed quam. Aenean semper odio eget erat tristique, in tempor diam suscipit. Integer vitae justo scelerisque, gravida neque a, egestas eros. Donec consectetur tempor pretium. Fusce ac nibh eu justo blandit cursus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque enim tellus, euismod id risus sit amet, ultricies eleifend metus. Pellentesque et ante et nulla convallis pellentesque. </p>
<p>Curabitur molestie libero ut massa rhoncus, nec porta sapien malesuada. Fusce congue non risus quis consectetur. Phasellus vitae nisl nec odio finibus gravida a eu lorem. Morbi blandit nulla ac diam rhoncus volutpat. Mauris nec tortor quis urna iaculis accumsan. Nulla laoreet augue tellus, eget condimentum quam congue sit amet. Pellentesque lacinia nisl condimentum nulla ultricies condimentum. Nunc sed vulputate nibh. Pellentesque nisl diam, volutpat nec interdum in, blandit sed diam. Aliquam vel lectus maximus, tincidunt velit id, fringilla purus. Cras quis massa non magna accumsan aliquet. Aliquam vel nisl sapien. Sed ut nisl porttitor, fringilla ante non, imperdiet ipsum. </p>
<p>Mauris luctus nibh mi, ut scelerisque nunc interdum nec. Ut elementum massa commodo sapien gravida blandit. Duis molestie venenatis hendrerit. Aliquam erat volutpat. Ut posuere dui dolor, sit amet pulvinar turpis euismod ac. Quisque tincidunt neque sit amet lectus molestie, sed consectetur nisl efficitur. Praesent malesuada, lorem vitae sagittis condimentum, enim orci ornare odio, sit amet interdum nisi ex at dolor. Donec elementum posuere quam, sollicitudin luctus nisl ultricies ut. Duis eu vestibulum ipsum. Quisque vitae ipsum iaculis ante molestie gravida. Nunc vehicula ut ex vitae pellentesque. Maecenas elementum rutrum risus, id ornare tellus tempor non. Ut posuere metus at ipsum posuere aliquam. Suspendisse eleifend dolor ac dictum pharetra. Nulla a sagittis ante, tristique tristique lorem. Praesent vitae eros malesuada, consequat nulla a, fermentum diam. </p>

<style>
	h1 {
	    font-size: 70px;
	    line-height: 90px;
	    font-family: DauphinPlain;
	    font-weight: 400;
	}
	hr {
    border: 0;
    height: 1px;
    background-image: linear-gradient(to right,rgba(0,0,0,0),rgba(0,0,0,.75),rgba(0,0,0,0));
	}
	p{
		text-align: justify;
		margin: 0 0 15px;
	}
</style>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h2 class="panel-title">
					<%= pluralize(obj.errors.count, "error")%>
					prohibited this article from being saved:
				</h2>
				<div class="panel-body">
					<ul>
						<% obj.errors.full_messages.each do |msg|%>
						<li><%= msg%></li>
						<%end%>				
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<%end%>

app/views/users/_form.html.erb
<%=render "shared/errors", obj: @user%>
<div class="row">
	<div class="col-xs-12">
		<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f|%>
		<div class="form-group">
			<div class="control-label col-sm-2">
					<%= f.label :username%><br/>
			</div>
			<div class="col-sm-8">		
					<%= f.text_field :username, class: "form-control",placeholder:"Enter username", autofocus: true%>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-sm-2">
					<%= f.label :email%><br/>
			</div>
			<div class="col-sm-8">
					<%= f.email_field :email, class: "form-control", placeholder: "Enter email"%>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-sm-2">
					<%= f.label :password%><br/>
			</div>
			<div class="col-sm-8">
					<%= f.password_field :password, class: "form-control", placeholder: "Enter password"%>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-10 col-sm-offset-2">
					<%=f.submit(@user.new_record? ? "Sign up" : "Update account",class: "btn btn-primary btn-lg")%>
			</div>
		</div>
		<%end%>
		<div class="col-xs-4 col-xs-offset-4">	
			[ <%=link_to "Cancel request and return to aricles listing", articles_path%> ]
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit account</h1>
<%= render 'form'%>

app/views/users/index.html.erb
<h1 align="center">All Fun Blog</h1>
<div align="center">
<%=will_paginate%>
	<% @users.each do |user| %>
		<ul class="listing">
			<div class="row">
				<div class="well col-md-4 col-md-offset-4">
					<li><%= link_to gravatar_for(user), user_path(user) %></li>
					<li class="article-title">
					  <%= link_to user.username, user_path(user) %>
					</li>
					<li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
				</div>
			</div>
		</ul>
	<%end%>
<%=will_paginate%>
</div>
	

app/views/users/new.html.erb
<h1 align="center">Sign up Fun Blog</h1>
<%= render 'form'%>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username%> page</h1>
<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<%= gravatar_for @user,size: 150 %>
	</div>
</div>
<h4 align="center"><%= @user.username%></h4>
<div class="center">
	<%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles%>
<div class="center">
	<%= will_paginate @user_articles %>
</div>